### ISSUE TITLE
Issue in README

### ISSUE THREAD

**Issue by mariano-f-r** [SocialCoin-Financial/getting-started#1]
You mentioned that Atom allows for pushing and pulling natively from GitHub without the use of a third party. Firstly, this is false, as under the hood Atom uses git to push and pull to GitHub.

-Savage

PS: Was bored; did this because of boredom

**Comment by LeftoverCantoneseFood** [comment]
bruh github is built on git....

there's no way to do it without git.

**Comment by mariano-f-r** [comment]
Yes, but you mentioned that atom allows for native pushing and pulling, when really it is all Git

**Comment by LeftoverCantoneseFood** [comment]
Stfu

**Comment by sergeant-savage** [comment]
Stupid, you closed the issue then opened it again by commenting lmfaooooo
